### ISSUE TITLE
Epic Loot Compatible Bug

### ISSUE THREAD

**Issue by Syprima** [ontrigger/ValheimPerformanceOptimizations#10]
Mod causes strange behavior of epic Loot mod. In adventure mode, tasks are not taken from the merchant and treasure maps are not bought (or not immediately). After clicking on accept the task / buy a treasure map, the message of target detection is displayed, but nothing happens. When you disable the optimization mod, everything works well and everything is added to the map. Epic Loot v0.8.1. I'm playing with a laptop and the optimization mod really helps, but please figure out what affects Epic Loot. Nothing happens in the console, no errors, which is weird.

**Comment by Syprima** [comment]
I recorded a video.
1. Optimization mod is on. Tasks are not accepted. The console is empty.
[https://yadi.sk/i/8316a6RDWvVwbw](url)
2. The optimization mod is disabled. Everything works, the console has records.
[https://yadi.sk/i/ZLtiNWZBFAPO1Q](url)

**Comment by MSchmoecker** [comment]
This is because of the recent threaded heightmap generation, we will take a look how to solve this issue. You can use version 0.3.1 in the meantime.

**Comment by Syprima** [comment]
Thank you!

**Comment by ontrigger** [comment]
Reopening until the issue is fixed
