### ISSUE TITLE
Please improve documentation

### ISSUE THREAD

**Issue by DragonMorkeleb** [ontrigger/ValheimPerformanceOptimizations#13]
Hey.
It would be helpful to improve documenation:
- Where exactly to the Environment.props file?
- Does it support mod managers such as Thunderstore Mod Manager from Overwolf? If so, does this affect where to put the props file?
- Is this mod also intended for dedicated servers? Any special considerations there?

**Comment by ontrigger** [comment]
The environment.props file is, as the title says, for developers only.
As it is a mod uploaded to thunderstore, it should work just fine
The mod works for both dedicated servers and for clients. You can mix and match however you want
