### ISSUE TITLE
Can someone help me compile the mod or just send me the new .dll file for the mod?

### ISSUE THREAD

**Issue by Deadxet** [ontrigger/ValheimPerformanceOptimizations#26]
I saw that the Jotunn.dll reference problem has been fixed. However, I have absolutely no idea how to compile the mod myself even after spending an hour now trying to figure it out. I would love to be able to use the mod again, sadly the latest verion on ThunderStore and Nexus are broken and produce a bunch of errors when launching the game (jotunn reference) causing the mod to simply not work at all.

Thankful for any help!

**Comment by ontrigger** [comment]
Fixed in 0.7.6
