### ISSUE TITLE
Farmables not shown visibly

### ISSUE THREAD

**Issue by sfjuocekr** [ontrigger/ValheimPerformanceOptimizations#29]
Things like berry bushes that are pooled are not resetting their visual markers of being ready.

With object pooling:

https://cdn.discordapp.com/attachments/586625814401908780/893550510290907207/Screenshot_20211001_193011.png

Without object pooling:

https://cdn.discordapp.com/attachments/586625814401908780/893551120377610270/Screenshot_20211001_193224.png

This happens after you farmed a bunch of berries, the "new" bushes all show up like this.

**Comment by sfjuocekr** [comment]
Thanks @ontrigger 

Might I ask what environment is used to build the mod? Just VSCode or does it build using Unity?

**Comment by ontrigger** [comment]
This was built with Rider, but you can also use visual studio
